const Constants = {
    ACTION_PRODUCT             : "ACTION_PRODUCT",
    ACTION_LOADING             : "ACTION_LOADING",
    ACTION_WAREHOUSE           : "ACTION_WAREHOUSE",
    ACTION_TAXCODE             : "ACTION_TAXCODE",
    ACTION_AUTHENTICATION      : "ACTION_AUTHENTICATION",
    ACTION_COMPANY             : "ACTION_COMPANY",
    ACTION_FORMDOC             : "ACTION_FORMDOC",
    ACTION_TRUCK               : "ACTION_TRUCK",
    ACTION_PRICE_TYPE          : "ACTION_PRICE_TYPE",
    ACTION_DESTINATION         : "ACTION_DESTINATION",
    ACTION_DESTINATION_RATE    : "ACTION_DESTINATION_RATE",
    ACTION_DESTINATION_DETAIL  : "ACTION_DESTINATION_DETAIL",
}

export default Constants