const Constants = {
    ACTION_PRODUCT        : "ACTION_PRODUCT",
    ACTION_LOADING        : "ACTION_LOADING",
    ACTION_WAREHOUSE      : "ACTION_WAREHOUSE",
    ACTION_TAXCODE        : "ACTION_TAXCODE",
    ACTION_AUTHENTICATION : "ACTION_AUTHENTICATION",
    ACTION_COMPANY        : "ACTION_COMPANY",
}

export default Constants